export interface PokemonTypes {
    'normal': string,
    'bug': string,
    'electric': string,
    'fighting': string,
    'ghost': string,
    'psychic': string,
    'flying': string,
    'steel': string,
    'ice': string,
    'poison': string,
    'fire': string,
    'dragon': string,
    'ground': string,
    'water': string,
    'dark': string,
    'rock': string,
    'grass': string,
    'fairy': string,
}
